
# make -f Makefile.mac

# The following lines assume packages 'netcdf' and 'netcdf-fortran' have been installed with macports 
NETCDF_INCLUDE=/opt/local/include/
NETCDF_LIB=/opt/local/lib/

FC=gfortran
FFLAGS=-I$(NETCDF_INCLUDE) -L$(NETCDF_LIB) -lnetcdf -lnetcdff -cpp


all: find

find: 
	${FC} ${FFLAGS} find_bounding_cells.f90 -o find_bounding_cells

mask: 
	${FC} ${FFLAGS} def_blanking_mask.f90 -o def_blanking_mask


